whitelist:
  - gcr.io/google_containers/
    - kube-apiserver-amd64
    - kube-controller-manager-amd64
    - kube-scheduler-amd64
    - kube-proxy-amd64
    - etcd-amd64
    - pause-amd64
    - k8s-dns-sidecar-amd64
    - k8s-dns-kube-dns-amd64
    - k8s-dns-dnsmasq-nanny-amd64
